version: 2
jobs:
  build:
    docker:
       - image: haskell:7.10.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cabal update
            cabal sandbox init
            cabal install --only-dependencies -j
            cabal configure
      - run:
          name: build
          command: |
            cabal build
            git submodule init
            git submodule update
            cd _site/ && git checkout master
            cabal run build

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy
          command: |
           git config --global user.email circleci@circleci
           git config --global user.name CircleCI
           cd _site/ && git status
           cd _site/ && git add --all
           cd _site/ && git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
           cd _site/ && git push origin master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: hakyll
